---
title: "Taking Stock"
author: "R. Joe Hendricks"
date: 29-12-2025
tags: ["nonfiction", "reflection", "meta-writing"]
---

**Prompt:** \
Write about how writing has shown up in your life this year-formally or informally.
What counted as writing? What didn't? Where did it surprise you?


**Response:** \
Writing is about as ever-present as math is for me. It shows up everywhere, sometimes sneaking in the background. I started writing a book this year, as a part of what would be NaNoWriMo. Unfortunately, the company that hosted it shut down. I didn't end up getting very far into it. I worked on other projects of writing, none of which really turned into much of anything. This was all done digitally, so I didn't have much opportunity to practice my penmanship. \

In terms of writing in the background, I enjoyed many tv shows and video games. One video game that I enjoyed in particular was Dispatch. The details and dialogue made it extremely enjoyable. I also enjoyed a show called the Pinkertons. The character writing and banter was exquisite. I think that's something I enjoy the most about fiction writing: the characters. At the beginning of the year, I spent most of my time re-reading my favorite book series (The Mysterious Benedict Society, highly recommend if you've never read) and it was a pleasure spending time with some of my favorite characters.

Writing is just about everywhere. It's inescapable. Much as I wish I could write more, my ADHD is kicking my butt, and I'm finding this hard to write so late (it's like 10:00 PM.) Writing is everywhere, in the media we consume especially. The world wouldn't be the same without it, and I feel blessed to be around so much of it, constantly.